// 1. use all clases

const { Sequelize, Model, DataTypes } = require('sequelize');

// 2. define the Database Connection
const sequelize = new Sequelize("company", "root", "P@ssw0rd_", {
    host: 'localhost',
    dialect: 'mysql',
    pool: {
        max: 5,
        min: 0,
        idle: 10000
    },
    define: {
        timestamps: false // supressing the TimeStamp generated by ORM
    }
});

// 3. importing the package
var dept = sequelize.import('./../models/department.js');


// 4. sync the model with the database using sequelize
// sequelize.sync({
//         force: false // default is true to create a table
//     })
//     .then(() =>
//         dept.create({
//             DeptId: 103,
//             DeptNo: 'Dept103',
//             DeptName: 'AC',
//             Location: 'Pune',
//             Capacity: 122
//         }))
//     .then((data) => console.log(data.toJSON()))
//     .catch((error) => { console.log(`Error Occured ${error}`) });

sequelize.sync({
        force: false // default is true to create a table
    })
    .then(() =>
        dept.findOne({ EmpNo: 101 })
    )
    .then((data) => console.log(JSON.stringify(data)))
    .catch((error) => { console.log(`Error Occured ${error}`) });